export enum AppLinks {
  ROOT = "/",
  LOGIN = "/login",
  USERS = "/users",
  NEWS = "/news",
  ADD_NEWS = "/news/new",
  EDIT_NEWS = "/news/:id",
  COLLECTIONS = "/collections",
  COLLECTIONS_ITEMS = "/collections-items",
  ADD_COLLECTIONS_ITEMS = ":id/collections-items/new",
  EDIT_COLLECTIONS_ITEMS = "/collections-items/:id",
  EXHIBITIONS = "/exhibitions",
  ADD_EXHIBITIONS = "/exhibitions/new",
  EDIT_EXHIBITIONS = "/exhibitions/:id",
  TICKETS = "/tickets",
}
